// ESLint flat config. Replaces `.eslintrc.json` + `next lint`, both removed in
// Next 16 (generated by `@next/codemod next-lint-to-eslint-cli`, then tidied).
//
// `next lint` supplied the ignore list implicitly; `eslint .` does not. Flat
// config ignores `node_modules` and nothing else, so every generated and
// vendored directory has to be named here or the lint step walks build output.
// `.claude/` matters most — sibling worktrees live there, so linting it means
// linting other branches' code. Same hazard as vitest sweeping worktree tests.
import { defineConfig, globalIgnores } from 'eslint/config'
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'

export default defineConfig([
  globalIgnores([
    '.next/**',
    '.claude/**',
    'out/**',
    'build/**',
    'coverage/**',
    'playwright-report/**',
    'test-results/**',
    'next-env.d.ts',
    'supabase/functions/**', // Deno runtime, linted by its own toolchain
    'docs/**', // vendored design handoffs, never ours to lint
    // Generated by the design-bundle import; gitignored, so it exists in some
    // checkouts and not others. It vendors its own React, whose internals trip
    // rules-of-hooks 17 times — which failed the pre-push hook, and therefore
    // every push, from whichever checkout happened to have the directory.
    'ds-bundle/**',
  ]),
  {
    extends: [...nextCoreWebVitals],
  },
  {
    // eslint-config-next 16 turns on the React Compiler-era hook rules. They
    // flag 20 pre-existing call sites across 18 files — deliberate patterns,
    // not defects (NotificationsMenu's seen-watermark setState is the clearest
    // case: it is the design, and it is verified working).
    //
    // Demoted to warnings ON PURPOSE so the Next 16 upgrade stays a Next 16
    // upgrade. Adopting these rules means a real refactor of effect-driven
    // state across the shell, the tour and half the dialogs, which deserves its
    // own branch and its own regression pass. Tracked in BACKLOG.md.
    // Do not silence them outright — the warnings are the to-do list.
    rules: {
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/refs': 'warn',
    },
  },
])
