import { NextRequest, NextResponse } from 'next/server'
import { updateSession } from '@/lib/supabase/middleware'

export async function middleware(request: NextRequest) {
  const { supabaseResponse, user, supabase } = await updateSession(request)
  const { pathname } = request.nextUrl

  // /auth/* are server-side verification handlers — never gate or bounce them,
  // they run before a session is fully established.
  if (pathname.startsWith('/auth')) {
    return supabaseResponse
  }

  // Terminal for a non-approved account. NOT in isAuthRoute below — that branch
  // redirects non-approved users to /pending, which would loop onto itself.
  if (pathname === '/pending') {
    return supabaseResponse
  }

  const isAuthRoute = pathname.startsWith('/login') || pathname.startsWith('/accept-invite') || pathname.startsWith('/signup')
  const isPublicRoute =
    pathname === '/' ||
    // Local-only quick-access page. Public so it renders with no session AND
    // while logged in as someone else — switching accounts is its whole job.
    // It guards itself: app/dev/page.tsx 404s outside development or against a
    // non-local database.
    pathname.startsWith('/dev') ||
    // CGU / CGV / confidentialité / mentions légales. These are linked from the
    // signup consent line and the landing footer — both seen by visitors with no
    // account — and advertised to anonymous crawlers by robots.ts / sitemap.ts.
    // Gating them bounced every one of those to /login.
    pathname.startsWith('/legal') ||
    pathname.startsWith('/apply') ||
    pathname.startsWith('/invite') ||
    pathname.startsWith('/join') ||
    pathname.startsWith('/api/stripe') ||
    pathname.startsWith('/api/cron') ||
    pathname === '/api/health'

  if (!user && !isAuthRoute && !isPublicRoute) {
    return NextResponse.redirect(new URL('/login', request.url))
  }

  // Everything below needs the users row: the approval gate on every gated
  // route, and the destination for someone who landed on an auth route or /.
  // Public routes are exempt — a logged-in visitor reading /legal or opening an
  // /apply link is no more privileged than the anonymous one beside them, and
  // paying a users lookup there would tax the CDN-served landing page.
  const needsProfile = !!user && (!isPublicRoute || pathname === '/')
  if (needsProfile) {
    const { data: profile } = await supabase
      .from('users').select('role, full_name, status').eq('id', user!.id)
      .single<{ role: string; full_name: string | null; status: string }>()

    // An orphaned/stale session: getClaims() verifies the JWT locally so `user`
    // is set, but there is no backing users row (account deleted, or the DB was
    // reset while the browser kept a still-valid access token). getUser() in the
    // server layouts rejects such a session, so redirecting it to /my-forms or
    // /dashboard bounces straight back to /login → infinite loop → blank screen.
    // Let the request through so the user can re-authenticate.
    if (!profile) {
      return supabaseResponse
    }

    // THE approval gate for the whole app surface. The (organizer) and
    // (student) layouts repeat it for their own groups, but a route outside
    // both — /billing and its service-role checkout, /admin — inherited nothing
    // and rendered for a pending signup. Gating here means a route is covered
    // the moment it exists, instead of the day someone remembers to add a
    // check. Non-approved means /pending, full stop.
    if (profile.status !== 'approved') {
      return NextResponse.redirect(new URL('/pending', request.url))
    }

    // Logged-in users hitting the auth routes or the marketing page (/) get sent
    // to their app. Handling / here (not in app/page.tsx) keeps the landing page
    // fully static so anonymous visitors are served from the CDN with no cold start.
    if (isAuthRoute || pathname === '/') {
      // A freshly-invited user has a session (set by /auth/confirm) but an empty
      // full_name. Let them finish setup on /accept-invite instead of bouncing them
      // to a dashboard for an account that isn't configured yet.
      const setupComplete = !!profile.full_name
      if (pathname.startsWith('/accept-invite') && !setupComplete) {
        return supabaseResponse
      }

      const dest = profile.role === 'organizer' ? '/dashboard' : '/my-forms'
      return NextResponse.redirect(new URL(dest, request.url))
    }
  }

  return supabaseResponse
}

export const config = {
  // Exclude framework assets AND the public metadata image routes generated by
  // next/og (app/icon.tsx, apple-icon.tsx, opengraph-image.tsx, twitter-image.tsx).
  // These have no file extension, so — unlike the old static app/icon.svg — they
  // are NOT caught by the `\\.(svg|png|…)$` rule and would otherwise hit the auth
  // gate below and 302 anon crawlers to /login, breaking the favicon, the OG/
  // Twitter share cards, and the JSON-LD logo (https://…/icon). They are public
  // brand images with no PII, exactly like favicon.ico/robots.txt/sitemap.xml.
  matcher: ['/((?!_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml|icon|apple-icon|opengraph-image|twitter-image|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)'],
}
